# Generated by Django 3.0.8 on 2020-07-15 13:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('size', models.CharField(default='40,42,44,46,48,50,52,54,56', max_length=40)),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Бежевый', 'Бежевый'), ('Шоколад', 'Шоколад'), ('Серый', 'Серый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Марсала', 'Марсала'), ('Розовый', 'Розовый'), ('Синий', 'Синий')], max_length=7)),
                ('length', models.CharField(choices=[('Длинное', 'Длинное'), ('Короткое', 'Короткое'), ('Средней длины', 'Средней длины')], max_length=13)),
                ('fabric_structure', models.CharField(blank=True, default='63% Wool; 17% Viscoze; 5% Poly', max_length=70, verbose_name='Тип ткани')),
                ('length_center_back', models.CharField(default='90', max_length=7, verbose_name='Длина пальто по центру спинки')),
                ('length_sleeve_neck', models.CharField(default='63-64', max_length=30, verbose_name='Длина рукава от горловины')),
                ('description', models.TextField()),
                ('sale', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='Sale %')),
                ('picture', models.ImageField(upload_to='coat')),
                ('add_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Пальто',
                'verbose_name_plural': 'Пальто',
            },
        ),
        migrations.CreateModel(
            name='DressModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('size', models.CharField(default='42,44', max_length=40)),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Бежевый', 'Бежевый'), ('Шоколад', 'Шоколад'), ('Серый', 'Серый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Марсала', 'Марсала'), ('Розовый', 'Розовый'), ('Синий', 'Синий')], max_length=7)),
                ('fabric_structure', models.CharField(blank=True, max_length=60, verbose_name='Тип ткани')),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='dress')),
                ('add_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Платье',
                'verbose_name_plural': 'Платья',
            },
        ),
        migrations.CreateModel(
            name='FaceMaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Бежевый', 'Бежевый'), ('Шоколад', 'Шоколад'), ('Серый', 'Серый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Марсала', 'Марсала'), ('Розовый', 'Розовый'), ('Синий', 'Синий')], max_length=7)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='face_mask')),
                ('add_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Защитная маска',
                'verbose_name_plural': 'Защитные маски',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=10, verbose_name='Телефон')),
                ('adress', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Киев', 'Киев'), ('Одеса', 'Одеса'), ('Днепр', 'Днепр'), ('Запорожье', 'Запорожье'), ('Львов', 'Львов'), ('Кривой Рог', 'Кривой Рог'), ('Николаев', 'Николаев'), ('Мариуполь', 'Мариуполь'), ('Винница', 'Винница'), ('Полтава', 'Полтава'), ('Чернигов', 'Чернигов'), ('Черкассы', 'Черкассы'), ('Хмельницкий', 'Хмельницкий'), ('Черновцы', 'Черновцы'), ('Житомир', 'Житомир'), ('Сумы', 'Сумы'), ('Ровно', 'Ровно'), ('Горловка', 'Горловка'), ('Ивано-Франковск', 'Ивано-Франковск'), ('Каменское', 'Каменское'), ('Кропивницкий', 'Кропивницкий'), ('Тернополь', 'Тернополь'), ('Кременчуг', 'Кременчуг'), ('Луцк', 'Луцк'), ('Белая-Церковь', 'Белая-Церковь'), ('Краматорск', 'Краматорск'), ('Мелитополь', 'Мелитополь'), ('Ужгород', 'Ужгород'), ('Никополь', 'Никополь'), ('Бердянск', 'Бердянск'), ('Бровары', 'Бровары'), ('Павлоград', 'Павлоград')], max_length=25)),
                ('whishlist', models.CharField(blank=True, default='', max_length=20)),
                ('shopping_basket', models.CharField(blank=True, default='', max_length=20)),
                ('person', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Заказ Оформлен', 'Заказ Оформлен'), ('Принят в работу', 'Принят в работу'), ('Отправлен', 'Отправлен'), ('Получен', 'Получен')], default='Заказ Оформлен', max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozze_app.Human')),
            ],
        ),
        migrations.CreateModel(
            name='ParkaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('size', models.CharField(default='40,42,44,46,48', max_length=40)),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Бежевый', 'Бежевый'), ('Шоколад', 'Шоколад'), ('Серый', 'Серый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Марсала', 'Марсала'), ('Розовый', 'Розовый'), ('Синий', 'Синий')], max_length=7)),
                ('length', models.CharField(choices=[('Длинное', 'Длинное'), ('Короткое', 'Короткое'), ('Средней длины', 'Средней длины')], max_length=13)),
                ('pockets', models.CharField(default='4', max_length=1, verbose_name='Карманы')),
                ('fur', models.CharField(default='опушка:  чернобурка (искусственный). Съемный, на пуговках.', max_length=70, verbose_name='Мех')),
                ('linig', models.CharField(default='мех  овчина (искусственный). В рукавах — подкладка полиестер.', max_length=70, verbose_name='Подкладка')),
                ('insulation', models.CharField(default='Thermal Silicon Insulations', max_length=40, verbose_name='Утеплитель')),
                ('length_back', models.CharField(default='80', max_length=7, verbose_name='Длина куртки')),
                ('length_sleeve', models.CharField(default='64-66', max_length=30, verbose_name='Длина рукава')),
                ('hood', models.CharField(default='втачной', max_length=10, verbose_name='Капюшон')),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='parka')),
                ('add_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Парка',
                'verbose_name_plural': 'Парки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('type_product', models.CharField(choices=[('Пальто', 'Пальто'), ('Платье', 'Платье'), ('Парка', 'Парка'), ('Защитная маска', 'Защитная маска')], max_length=14)),
                ('name', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('color', models.CharField(choices=[('Белый', 'Белый'), ('Черный', 'Черный'), ('Бежевый', 'Бежевый'), ('Шоколад', 'Шоколад'), ('Серый', 'Серый'), ('Зеленый', 'Зеленый'), ('Красный', 'Красный'), ('Марсала', 'Марсала'), ('Розовый', 'Розовый'), ('Синий', 'Синий')], max_length=7)),
                ('size', models.CharField(default='40,42,44,46,48,50,52,54,56', max_length=40)),
                ('length', models.CharField(choices=[('Длинное', 'Длинное'), ('Короткое', 'Короткое'), ('Средней длины', 'Средней длины')], max_length=13)),
                ('fabric_structure', models.CharField(blank=True, max_length=40, verbose_name='Тип ткани')),
                ('description', models.TextField()),
                ('sale', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='Sale %')),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arive_date', models.DateField()),
                ('details', models.CharField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozze_app.Order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozze_app.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ozze_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('product_type', models.CharField(choices=[('Coat', 'Coat'), ('Dress', 'Dress'), ('Parka', 'Parka'), ('Face_mask', 'Face_mask')], default='', max_length=9)),
                ('product_id', models.PositiveIntegerField(unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session_key')},
            },
        ),
    ]
