# Generated by Django 3.0.8 on 2020-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='product_id',
            field=models.PositiveIntegerField(),
        ),
    ]
