# Generated by Django 3.0.8 on 2020-07-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0005_auto_20200715_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coatmodel',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Цена со скидкой'),
        ),
    ]
