# Generated by Django 3.0.8 on 2020-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0006_auto_20200715_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='coatmodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='coat'),
        ),
        migrations.AddField(
            model_name='coatmodel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='coat'),
        ),
        migrations.AddField(
            model_name='coatmodel',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='coat'),
        ),
    ]
