# Generated by Django 3.0.8 on 2020-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0008_auto_20200717_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coatmodel',
            name='sale',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=7, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
