# Generated by Django 3.0.8 on 2020-07-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0009_auto_20200717_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AddField(
            model_name='dressmodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='coat'),
        ),
        migrations.AddField(
            model_name='parkamodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='coat'),
        ),
        migrations.AddField(
            model_name='parkamodel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='coat'),
        ),
        migrations.AlterField(
            model_name='dressmodel',
            name='picture',
            field=models.ImageField(upload_to='dress', verbose_name='Главная картинка'),
        ),
        migrations.AlterField(
            model_name='parkamodel',
            name='picture',
            field=models.ImageField(upload_to='parka', verbose_name='Главная картинка'),
        ),
    ]
