# Generated by Django 3.0.8 on 2020-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0010_auto_20200717_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='facemaskmodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='face_mask'),
        ),
        migrations.AddField(
            model_name='facemaskmodel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='face_mask'),
        ),
        migrations.AlterField(
            model_name='dressmodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='dress'),
        ),
        migrations.AlterField(
            model_name='parkamodel',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='parka'),
        ),
        migrations.AlterField(
            model_name='parkamodel',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='parka'),
        ),
    ]
