# Generated by Django 3.0.8 on 2020-07-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ozze_app', '0011_auto_20200717_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facemaskmodel',
            name='picture3',
        ),
    ]
